/**
 * dualViewStore.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Zustand store for the dual-view toggle (3D Preview ↔ Workshop Mode) and
 * local progress state that mirrors Firestore.
 *
 * Data model for a single page entry (mirrors the Firestore project doc):
 *   users/{uid}/projects/{projectId}
 *     ├─ rows: FoldRow[]          ← generated by algorithm.ts
 *     ├─ completedPages: number[] ← set of page indices marked done
 *     ├─ createdAt: Timestamp
 *     └─ userId: string
 */

import { create } from "zustand";
import { persist } from "zustand/middleware";

// ── Types ────────────────────────────────────────────────────────────────────

/** A single row from the fold algorithm output. */
export interface FoldRow {
  /** 1-based page number to display to the user. */
  page: number;
  /** Start measurement in cm (top of mark from top of page). */
  startCm: number;
  /** End measurement in cm. */
  endCm: number;
  /** "MMF" | "CF" — fold method for this mark. */
  method: "MMF" | "CF";
}

export type ViewMode = "3d" | "workshop";

interface DualViewState {
  // ── View toggle ──────────────────────────────────────────────────────────
  mode: ViewMode;
  setMode: (m: ViewMode) => void;

  // ── Pattern data (set by ConfigPanel / algorithm) ────────────────────────
  rows: FoldRow[];
  projectId: string | null;
  pageHeightCm: number;

  setPatternData: (rows: FoldRow[], projectId: string, pageHeightCm: number) => void;

  // ── Local progress (kept in sync with Firestore by useWorkshopSync) ──────
  completedPages: Set<number>;
  togglePage: (page: number) => void;
  setCompletedPages: (pages: number[]) => void;

  // ── Derived ──────────────────────────────────────────────────────────────
  progressPct: () => number;
}

// ── Store ────────────────────────────────────────────────────────────────────

export const useDualViewStore = create<DualViewState>()(
  persist(
    (set, get) => ({
      // View
      mode: "workshop",
      setMode: (m) => set({ mode: m }),

      // Pattern
      rows: [],
      projectId: null,
      pageHeightCm: 20,
      setPatternData: (rows, projectId, pageHeightCm) =>
        set({ rows, projectId, pageHeightCm }),

      // Progress
      completedPages: new Set<number>(),
      togglePage: (page) =>
        set((s) => {
          const next = new Set(s.completedPages);
          next.has(page) ? next.delete(page) : next.add(page);
          return { completedPages: next };
        }),
      setCompletedPages: (pages) =>
        set({ completedPages: new Set(pages) }),

      // Derived
      progressPct: () => {
        const { rows, completedPages } = get();
        if (!rows.length) return 0;
        const uniquePages = new Set(rows.map((r) => r.page));
        return Math.round((completedPages.size / uniquePages.size) * 100);
      },
    }),
    {
      name: "mekapele-dual-view",
      // Sets are not JSON-serialisable — convert to/from array.
      partialize: (s) => ({
        mode: s.mode,
        completedPages: [...s.completedPages],
        projectId: s.projectId,
      }),
      merge: (persisted: any, current) => ({
        ...current,
        ...persisted,
        completedPages: new Set<number>(persisted?.completedPages ?? []),
      }),
    }
  )
);
